//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelRes.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeCreate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeCreate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TolokaStudio.Resources.Models.Employee.EmployeeCreate", typeof(EmployeeCreate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення автора.
        /// </summary>
        public static string Author_Creation {
            get {
                return ResourceManager.GetString("Author_Creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати автора.
        /// </summary>
        public static string Edit_Author {
            get {
                return ResourceManager.GetString("Edit_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пошта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iм&apos;я.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детальніше про автора.
        /// </summary>
        public static string HtmlDetail {
            get {
                return ResourceManager.GetString("HtmlDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть пошту.
        /// </summary>
        public static string Required_Email {
            get {
                return ResourceManager.GetString("Required_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть ім&apos;я.
        /// </summary>
        public static string Required_FirstName {
            get {
                return ResourceManager.GetString("Required_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть аватар.
        /// </summary>
        public static string Required_Image {
            get {
                return ResourceManager.GetString("Required_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть прізвище.
        /// </summary>
        public static string Required_LastName {
            get {
                return ResourceManager.GetString("Required_LastName", resourceCulture);
            }
        }
    }
}
